- name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY1 }}
          port: 22
          command_timeout: 30m  # Adds extra time for the pull and restart
          script: |
            cd ~/flask-app
            git pull origin ${{ github.ref_name }}

            # Kill old process
            pkill -f "app.py" || true

            # Launch new process
            if [ "${{ github.ref_name }}" == "dev" ]; then
              nohup /usr/bin/python3 app.py > dev.log 2>&1 &
              sleep 2 # Give it a second to start
            fi

            if [ "${{ github.ref_name }}" == "main" ]; then
              nohup /usr/bin/python3 app.py > live.log 2>&1 &
              sleep 2
            fi
            
            echo "Deployment successful"
