name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ dev, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY1 }}
          port: 22
          script: |
            cd ~/flask-app
            git pull origin ${{ github.ref_name }}
            if [ "${{ github.ref_name }}" == "dev" ]; then
              pkill -f "app.py" || true
              APP_ENV=dev APP_PORT=4000 nohup /usr/bin/python3 app.py > dev.log 2>&1 &
              disown
            fi
            if [ "${{ github.ref_name }}" == "main" ]; then
              pkill -f "app.py" || true
              APP_ENV=live APP_PORT=5000 nohup /usr/bin/python3 app.py > live.log 2>&1 &
              disown
            fi
